#kind: pipeline
#type: exec
#name: create-image
#
#steps:
#  - name: create
#    commands:
#      - make build-image
#
#---

kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:alpine
    commands:
      - apk add build-base
      - cd src
      - go test
      - go build
      #- go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  #- name: lint
  #  pull: never
  #  image: crescent-lang:latest
  #  commands:
  #    - apk add --update curl docker openrc --no-cache
  #    - dockerd
  #    - cd /usr/local
  #    - curl -L https://dl.dagger.io/dagger/install.sh | sh
  #    - cd -
  #    - sudo dagger do lint --log-format plain



#  - name: lint
#    image: golang:alpine
#    commands:
#      - apk add build-base
#      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#      - golangci-lint run --enable-all
#


#  - name: Test
#    image: alpine
#    commands:
#      - cd /usr/local
#      - curl -L https://dl.dagger.io/dagger/install.sh | sudo sh
#      - cd -