kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:

  - name: lint
    image: golang:alpine
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golang-ci lint run

  - name: test
    image: golang:alpine
    commands:
      - go test
      - go build
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golang-ci lint run





#  - name: Test
#    image: alpine
#    commands:
#      - cd /usr/local
#      - curl -L https://dl.dagger.io/dagger/install.sh | sudo sh
#      - cd -