kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golang:alpine
    commands:
      - apk add --update curl docker openrc sudo --no-cache
      - cd /usr/local
      - curl -L https://dl.dagger.io/dagger/install.sh | sh
      - cd -
      - dagger do lint --log-format plain



#  - name: lint
#    image: golang:alpine
#    commands:
#      - apk add build-base
#      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#      - golangci-lint run --enable-all
#
#  - name: test
#    image: golang:alpine
#    commands:
#      - go test
#      - go build
#      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#


#  - name: Test
#    image: alpine
#    commands:
#      - cd /usr/local
#      - curl -L https://dl.dagger.io/dagger/install.sh | sudo sh
#      - cd -